%YAML 1.3
---
- Key: [Dictation, released]
- Execute: [flatpak, run, com.google.Chrome, --profile-directory=Default, 'https://gemini.google.com']
...
---
- Key: [Emoji, released]
- Execute: gnome-characters
...
---
- Key: [Mute Microphone, released]
- KeyPress:
  - XF86_AudioMicMute
  - click
...
---
- Key: [Smart Shift, released]
- KeyPress:
  - [Alt_L, Tab]
  - click
...
---
- Key: [Mouse Gesture Button, released]
- KeyPress:
  - Super_L
  - click
...
---
- Test: [thumb_wheel_down, 25]
- KeyPress:
  - [Control_L, Super_L, l]
  - click
...
---
- Test: [thumb_wheel_up, 25]
- KeyPress:
  - [Control_L, Super_L, h]
  - click
...
